# Generated by Django 5.1 on 2025-11-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Skateshop', '0002_cliente_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={},
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre_empresa',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pais',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
