# Generated by Django 5.1 on 2025-11-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Skateshop', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
        migrations.AddField(
            model_name='cliente',
            name='compra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_cliente',
            field=models.CharField(default='CLI001', max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
