# Generated by Django 5.1 on 2025-11-12 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Skateshop', '0005_auto_20251112_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
    ]
