# Generated by Django 5.1 on 2025-11-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Skateshop', '0007_alter_cliente_id_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='compra',
        ),
        migrations.AddField(
            model_name='cliente',
            name='compra',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='app_Skateshop.producto'),
        ),
    ]
