# Generated by Django 5.1 on 2025-11-18 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Skateshop', '0008_remove_cliente_compra_cliente_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('clientes_atendidos', models.ManyToManyField(blank=True, related_name='empleados_atendieron', to='app_Skateshop.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='app_Skateshop.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_realizadas', to='app_Skateshop.empleado')),
                ('productos', models.ManyToManyField(related_name='ventas', to='app_Skateshop.producto')),
            ],
        ),
    ]
